feat(ci): add music library targets and staging for audio plugins

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -412,7 +412,7 @@ jobs:
             -DUSE_SFML=ON
 
       - name: Build
-        run: cmake --build --preset ${{ matrix.preset }} --target r-type_client r-type_server rtype-display-sfml rtype-graphic-background-lobby rtype-graphic-background-asteroidsSpace rtype-graphic-background-labs
+        run: cmake --build --preset ${{ matrix.preset }} --target r-type_client r-type_server rtype-display-sfml rtype-graphic-background-lobby rtype-graphic-background-asteroidsSpace rtype-graphic-background-labs rtype-graphic-music-chillMusic rtype-graphic-music-battleMusic
 
       - name: Prepare Windows dist (exe + DLLs only)
         if: matrix.os == 'windows-latest'
@@ -437,6 +437,13 @@ jobs:
             exit 1
           fi
           cp -v build/lib/background/**/*.dll build/dist/client/plugins/background/
+
+          echo "Staging Audio lib"
+          if ! ls build/lib/music/**/*.dll >/dev/null 2>&1; then
+            echo "Error: No music lib found"
+            exit 1
+          fi
+          cp -v build/lib/music/**/*.dll build/dist/client/plugins/music/
 
           if ! ls build/vcpkg_installed/x64-windows/bin/*.dll >/dev/null 2>&1; then
             echo "Error: No DLLs found for client"
